<a href="https://colab.research.google.com/github/Shikher-jain/Data_Science/blob/main/DL/PYTORCH/CampusX_PT/Pytorch_CampusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

In [ ]:
print(torch.cuda.is_available())

In [ ]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("No GPU available")

In [ ]:
torch.empty(2, 3)

In [ ]:
torch.zeros(2, 3)

In [ ]:
torch.ones(2, 3)

In [ ]:
torch.rand(2, 3)

In [ ]:
torch.manual_seed(101)
torch.rand(2, 3)

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

In [ ]:
print(torch.arange(1,11,2))
print(torch.linspace(1,10,4))
print(torch.eye(6))
print(torch.full((2,3),2.4))

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

In [ ]:
 torch.zeros_like(x)

In [ ]:
torch.ones_like(x)

In [ ]:
x.dtype,y.dtype

In [ ]:
y = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
y.shape,y.dtype

In [ ]:
y.to((torch.int32))
x.dtype,y.dtype

In [ ]:
x.dtype,y.dtype

In [ ]:
torch.rand_like(x,dtype=torch.float64)

In [ ]:
torch.cat((x,x,x), dim=0)

In [ ]:
print("X :" ,x)
print("Y :" ,y)

print("ADD")
print(x+y)
print(torch.add(x,y))
print(x.add(y))

print("SUBTRACT")
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

print("MULTIPLY")
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

print("DIVIDE")
print(x/y)
print(torch.div(x,y))
print(x.div(y))

print("POWER")
print(x**y)
print(torch.pow(x,y))
print(x.pow(y))

print("SQRT")
print(torch.sqrt(x))
print(x.sqrt())

print("EXP")
print(torch.exp(x))
print(x.exp())

print("LOG")
print(torch.log(x))
print(x.log())

print("SIN")
print(torch.sin(x))
print(x.sin())

print("COS")
print(torch.cos(x))
print(x.cos())

print("TAN")
print(torch.tan(x))
print(x.tan())

print("ABS")
print(torch.abs(x))
print(x.abs())

print("SUM")
print(torch.sum(x))
print(x.sum())

print("MEAN")
print(torch.mean(y))
print(y.mean())

print("MAX")
print(torch.max(x))
print(x.max())

print("MIN")
print(torch.min(x))
print(x.min())

print("ARGMAX")
print(torch.argmax(x))
print(x.argmax())

print("ARGMIN")
print(torch.argmin(x))
print(x.argmin())

print("EQUAL")
print(torch.eq(x,y))
print(x.eq(y))

print("NOT EQUAL")
print(torch.ne(x,y))
print(x.ne(y))

print("Std")
print(torch.std(y))
print(y.std())

print("Var")
print(torch.var(y))
print(y.var())

print("Transpose")
print(torch.t(x))
print(x.t())

print("Transpose")
print(torch.transpose(x,0,1))
print(x.transpose(0,1))

print("Reshape")
print(torch.reshape(x,(3,2)))
print(x.reshape(3,2))

print("Reshape")
print(torch.reshape(x,(6,1)))
print(x.reshape(6,1))

print("Reshape")
print(torch.reshape(x,(1,6)))
print(x.reshape(1,6))


print('dot')
print(torch.dot(x[0],x[1]))
print(x[0].dot(x[1]))

In [ ]:
print("Sigmoid")
x,torch.sigmoid(x)

In [ ]:
print("ReLU")
x,torch.relu(x)

In [ ]:
print("Softmax")
x =x.to(torch.float64)
x, torch.softmax(x, dim=0), torch.softmax(x, dim=1)

# ====================

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
x.grad
x , y

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
z = torch.sin(y)
# y.backward()
z.backward()
x.grad, y.grad, z.grad
# x , y , z

# ================

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [ ]:
w,y,w,b

In [ ]:
z = w*x+b
y_pred = torch.sigmoid(z)
loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))

In [ ]:
z,y_pred,loss

In [ ]:
loss.backward()

In [ ]:
w.grad, b.grad

# ===============

In [ ]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y = x**2
# y.backward()
x.grad

In [ ]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y1 = (x**2).mean()
y1.backward()
x.grad,x.grad.zero_

# =======training pipeline

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

In [218]:
df.shape

(569, 31)

In [217]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [219]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [220]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [221]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [222]:
X_train

array([[-0.41446618,  0.69650788, -0.32325002, ...,  1.20481581,
         0.82165818,  2.18929493],
       [-0.63155225,  0.78942971, -0.5853744 , ..., -0.12374648,
        -1.16719913,  0.51684155],
       [-0.44508088, -0.41378883, -0.49558371, ..., -1.22082368,
        -1.20972404, -1.28751906],
       ...,
       [-0.66216695, -0.27798001, -0.70777965, ..., -0.81790152,
        -0.1956685 , -0.5367878 ],
       [-0.4562135 ,  1.05628214, -0.42673077, ...,  0.81300252,
         0.78240442,  1.03849936],
       [-0.09440339,  0.05082031, -0.08729781, ...,  0.97963576,
         0.44874743,  1.1687781 ]])

In [223]:
y_train

229    M
382    B
429    B
137    B
417    M
      ..
268    B
19     B
52     B
64     M
435    M
Name: diagnosis, Length: 455, dtype: object

In [224]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [225]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1])

In [226]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [227]:
X_train_tensor.shape

torch.Size([455, 30])

In [228]:
y_train_tensor.shape

torch.Size([455])

In [229]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [238]:
learning_rate = 0.1
epochs = 25

In [239]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.380054042214011
Epoch: 2, Loss: 3.2378292230914347
Epoch: 3, Loss: 3.0941875380574273
Epoch: 4, Loss: 2.949314333635091
Epoch: 5, Loss: 2.7989117280264915
Epoch: 6, Loss: 2.645347292476786
Epoch: 7, Loss: 2.494208171789467
Epoch: 8, Loss: 2.342039537211255
Epoch: 9, Loss: 2.1879924513071436
Epoch: 10, Loss: 2.0345019172826606
Epoch: 11, Loss: 1.8820589872989373
Epoch: 12, Loss: 1.7343171871410514
Epoch: 13, Loss: 1.5948947376711446
Epoch: 14, Loss: 1.4635231830953541
Epoch: 15, Loss: 1.3443757426135365
Epoch: 16, Loss: 1.238015848559683
Epoch: 17, Loss: 1.1475372891027693
Epoch: 18, Loss: 1.0726970024435127
Epoch: 19, Loss: 1.0123104372191332
Epoch: 20, Loss: 0.9644054048016849
Epoch: 21, Loss: 0.9266209961764488
Epoch: 22, Loss: 0.8966467023810747
Epoch: 23, Loss: 0.8725116318548561
Epoch: 24, Loss: 0.8526872371048105
Epoch: 25, Loss: 0.8360626993433362

In [233]:
model.bias

tensor([-0.1230], dtype=torch.float64, requires_grad=True)

In [234]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.700061559677124